In [4]:
import torch
import pandas as pd
import matplotlib as plt
!nvidia-smi

ModuleNotFoundError: No module named 'pandas'

In [ ]:
scaler=torch.tensor(7)
scaler
print(torch.__version__)

2.3.1+cpu


In [4]:
TENSOR=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
TENSOR
TENSOR.ndim


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedan\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\vedan\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedan\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

2

In [5]:
num = torch.randn(2,3)
num

tensor([[-0.8761, -0.5028, -0.3293],
        [-0.5969, -0.6010, -0.4962]])

In [6]:
#torch.ones
#torch.zeroes

In [7]:
tensor =torch.tensor([1,2,3])
tensor2=torch.tensor([6,6,6])
lol=tensor@tensor2
lol
#just use torch.matmul(x,y) or @

tensor(36)

In [8]:
#shapes
tenA=torch.rand(3,2)
tenB=torch.rand(3,2)
#transpose
tenC=tenB.T
torch.matmul(tenA,tenC)

tensor([[0.9588, 0.1545, 0.4881],
        [0.5439, 0.0933, 0.3604],
        [0.7786, 0.1231, 0.3613]])

In [9]:
#finding mean media mode 
torch.max(tenA)

tensor(0.9989)

In [10]:
tenA=tenA.reshape(2,3)
tenA

tensor([[0.3828, 0.9989, 0.6485],
        [0.1281, 0.1300, 0.9949]])

In [5]:
x = torch.randn(2, 3, 5)
x.size()
torch.Size([2, 3, 5])
torch.permute(x, (2, 0, 1)).size()
torch.Size([5, 2, 3])

torch.Size([5, 2, 3])